# 1st and 2nd lines area special in python code
# TODO Implementar limpar_tda()
# TODO EPSG SER UM DROPDOWN COM AS OPÇÕES
# TODO FAZER VÁRIOS PROJETOS SÓ PRA TROCAR O POSICIONAMENTO DO NOME
# TODO FAZER VÁRIOS PROJETOS SÓ PRA MUDAR O TAMANHO DAS GRADES
# TODO DROPDOWN COM VARIAS ESCALAS PRÉ-PRONTAS
# TODO CHECKBOX + LABEL E ENTRY ESCALA PERSONALIZADA
# TODO TROCAR DE PROJETO SE AS GRANDE FICAREM POPULOSAS DEMAIS
# TODO SALVAR TODAS AS IMGS DE PRE-VIZUALIZACAO


""" CONCLUIDOS """
# ATIVAR / DESATIVAR: LIMITES, GLEBAS, ASSENTAMENTOS, ETC
# MAKE SURE TO ADD BUFFER 300 TO AREA DE LIMITACAO
# AJEITAR A OPTIONBOX DE .TXT E .SHP, ALGO DEU ERRADO

